trigger:
  branches:
   include:
     - master
  

pool:
  vmImage: ubuntu-latest
  

variables:
  #- group: ade-variables
  AZURE_RESOURCE_GROUP: "adedemorg"
  AZURE_LOCATION: "westeurope"
  AZURE_CATALOG: "CentralCatalog"
  AZURE_ADE_NAME: "dc-devbox003"
  ADO_PAT: "https://abndevcenterkeyvault.vault.azure.net/secrets/adopat"
  REPO: "https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ade-demo"

stages:
- stage: Create_Catalog
  jobs:
  - job: create_catalog 
      
    steps:
    # Update devcenter extension
    - task: Bash@3
      displayName: Install DevCenter CLI Extension
      inputs:
        targetType: 'inline'
        script: 'az extension add --name devcenter --upgrade'
    - task: AzureCLI@2
      displayName: Create a catalog
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter admin catalog create --ado-git path="/Environments" branch="main" secret-identifier="https://abndevcenterkeyvault.vault.azure.net/secrets/adopat" uri="https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ade-demo" --name $(AZURE_CATALOG) --dev-center-name $(AZURE_ADE_NAME) --resource-group $(AZURE_RESOURCE_GROUP)'