# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:  
  AZURE_RESOURCE_GROUP: "devcenterdemo-rg"
  

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  displayName: Configure Dev Center and its components
  inputs:
    azureSubscription: 'masterconnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      DEPLOYINGUSERID=$(az ad signed-in-user show --query id -o tsv) 
      echo $DEPLOYINGUSERID    
