trigger:
  branches:
   include:
     - master
  

pool:
  vmImage: ubuntu-latest
  

variables:
  #- group: ade-variables
 
  AZURE_RESOURCE_GROUP: "ade-rg14"
  AZURE_LOCATION: "westeurope"
  AZURE_CATALOG: "Catalog-Staticweb"
  AZURE_ADE_NAME: "dc-devbox0014"
  Azure_KEYVAULT: "kv-dboxjom74ygdqtcra"
  REPO: "https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ADE-CATALOG"
  ENVIRONMENT_DEFINITION_PATH: "/infrastructure-templates"
  
  

stages:
- stage: Create_Catalog
  jobs:
  - job: create_catalog 
      
    steps:
    # Update devcenter extension
    - task: Bash@3
      displayName: Install DevCenter CLI Extension
      inputs:
        targetType: 'inline'
        script: 'az extension add --name devcenter --upgrade'
    
    - task: AzureCLI@2
      displayName: Create Dev Center catalog
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter admin catalog create --ado-git path=$ENVIRONMENT_DEFINITION_PATH branch="main" secret-identifier="https://$(Azure_KEYVAULT).vault.azure.net/secrets/dcc" uri=$REPO --name $(AZURE_CATALOG) --dev-center-name $(AZURE_ADE_NAME) --resource-group $(AZURE_RESOURCE_GROUP)'