# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:  
  #- group: ade-variables  
  LOCATION: "westeurope"
  AZURE_RESOURCE_GROUP: "ade-rg10"
  AZURE_DEVCENTER: "devbox0010"
  AZURE_PROJECT: ""
  AZURE_KEYVAULT: "pocmasterkeysvault1610"
  CATALOG_REPO: 'https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ADE-CATALOG'
  
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'masterconnection'
    KeyVaultName: 'pocmasterkeysvault1610'
    SecretsFilter: 'adopat'
    RunAsPreJob: true
- task: AzureCLI@2
  displayName: Configure Dev Center and its components
  inputs:
    azureSubscription: 'masterconnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |    
      
      
      #Get the deploying users id for RBAC assignments
      #DEPLOYINGUSERID=$(az ad signed-in-user show --query id -o tsv)
      DEPLOYINGUSERID='6e4c3017-00f7-440d-ac5c-695cf98dd060'
      # SERVICE_PRINCIPAL_ID=$(az account show --query user.name -o tsv)
      # DEPLOYINGUSERID=$(az ad sp show --id $SERVICE_PRINCIPAL_ID  --query id -o tsv)
      AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            
      #Create resource group
      az group create -n $AZURE_RESOURCE_GROUP -l westeurope
      
      #Deploy the common infrastructure
      #DEVCENTERNAME=$(az deployment group create -g $AZURE_RESOURCE_GROUP -f ADE-Config/bicep/common.bicep -p nameseed=$AZURE_DEVCENTER devboxProjectUser=$DEPLOYINGUSERID --query 'properties.outputs.devcenterName.value' -o tsv)           
      DEVCENTERNAME='dc-devbox0010'
      #Configure and Deploy Microsoft Dev Box Infrastructure            
      az deployment group create -g $AZURE_RESOURCE_GROUP -f ADE-Config/bicep/ade.bicep -p devcenterName=$DEVCENTERNAME catalogRepoUri=$CATALOG_REPO catalogRepoPat=$adopat adeProjectUser=$DEPLOYINGUSERID
      
      # ADD Dev center as owner in the subscription
      AZURE_DEVCENTER_PRINCIPAL_ID=$(az resource list -n $DEVCENTERNAME --query [*].identity.principalId --out tsv)      

      az role assignment create \
        --scope /subscriptions/$AZURE_SUBSCRIPTION_ID \
        --role Owner \
        --assignee-object-id $AZURE_DEVCENTER_PRINCIPAL_ID \
        --assignee-principal-type ServicePrincipal      
  env:
    adopat: $(adopat)    
