trigger:
  branches:
   include:
     - master
  

pool:
  vmImage: ubuntu-latest
  

variables:
  #- group: ade-variables
  AZURE_SUBSCRIPTION_ID: "989f76fd-5edb-4aa1-b014-f989e1918adc"
  AZURE_RESOURCE_GROUP: "adedemorg"
  AZURE_LOCATION: "westeurope"
  AZURE_CATALOG: "Catalog1"
  AZURE_ADE_NAME: "dc-devbox003"
  
  

stages:
- stage: Create_Catalog
  jobs:
  - job: create_catalog 
      
    steps:
    # Update devcenter extension
    - task: Bash@3
      displayName: Install DevCenter CLI Extension
      inputs:
        targetType: 'inline'
        script: 'az extension add --name devcenter --upgrade'
    - task: AzureCLI@2
      displayName: Give access for the ADE on Subscription
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          AZURE_DEVCENTER_PRINCIPAL_ID=$(az resource list -n $AZURE_ADE_NAME --query [*].identity.principalId --out tsv)
          
          az role assignment create \
            --scope /subscriptions/$AZURE_SUBSCRIPTION_ID \
            --role Owner \
            --assignee-object-id $AZURE_DEVCENTER_PRINCIPAL_ID \
            --assignee-principal-type ServicePrincipal

          # az role assignment create \
          #   --scope $AZURE_KEYVAULT_ID \
          #   --role "Key Vault Secrets User" \
          #   --assignee-object-id $AZURE_DEVCENTER_PRINCIPAL_ID \
          #   --assignee-principal-type ServicePrincipal  
    - task: AzureCLI@2
      displayName: Create a catalog
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter admin catalog create --ado-git path="/Environments" branch="main" secret-identifier="https://abndevcenterkeyvault.vault.azure.net/secrets/adopat" uri="https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ade-demo" --name $(AZURE_CATALOG) --dev-center-name $(AZURE_ADE_NAME) --resource-group $(AZURE_RESOURCE_GROUP)'