trigger:
  branches:
   include:
     - master
  

pool:
  vmImage: ubuntu-latest
  

variables:
  #- group: ade-variables
  AZURE_RESOURCE_GROUP: "my-dev-center-rg"
  AZURE_LOCATION: "westeurope"
  AZURE_CATALOG: "abn"
  AZURE_ADE_NAME: "abndevcenter-dev-center"
  ENVIRONMENT_TYPE: "Dev"
  ENVIRONMENT_NAME: "frontend-$(ENVIRONMENT_TYPE)"
  AZURE_PROJECT: "projectfrontend"
  Environment_Definition_Name: "app-service"
  

stages:
- stage: Create_Environment
  jobs:
  - job: create_env  
      
    steps:
    # Update devcenter extension
    - task: Bash@3
      displayName: Install DevCenter CLI Extension
      inputs:
        targetType: 'inline'
        script: 'az extension add --name devcenter --upgrade'
    - task: AzureCLI@2
      displayName: Create Environment
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az devcenter dev environment create --dev-center-name $(AZURE_ADE_NAME) --environment-name $(ENVIRONMENT_NAME) --environment-type $(ENVIRONMENT_TYPE) --project $(AZURE_PROJECT) \
           --catalog-name $(AZURE_CATALOG) --environment-definition-name $(Environment_Definition_Name) \
           --parameters '{ "name": "$(ENVIRONMENT_NAME)" }' --only-show-errors
    
    