trigger:
  branches:
   include:
     - master
  

pool:
  vmImage: ubuntu-latest
  

variables:
  #- group: ade-variables
  AZURE_RESOURCE_GROUP: "my-dev-center-rg"
  AZURE_LOCATION: "westeurope"
  AZURE_CATALOG: "CentralAbnCatalog"
  AZURE_ADE_NAME: "abndevcenter-dev-center"
  ENVIRONMENT_TYPE: "Dev"
  ENVIRONMENT_NAME: "abndc-$(ENVIRONMENT_TYPE)"
  AZURE_PROJECT: "abndevcenter-project"
  Environment_Definition_Name: "AzureWebApp"
  AZURE_TENANT_ID: "835f6712-aeca-416a-8b76-d4dad8d12381"
  

stages:
- stage: Create_Environment
  jobs:
  - job: create_env  
      
    steps:
    # Update devcenter extension
    - task: Bash@3
      displayName: Install DevCenter CLI Extension
      inputs:
        targetType: 'inline'
        script: 'az extension add --name devcenter --upgrade'
    - task: AzureCLI@2
      displayName: Create a catalog
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter admin catalog create --ado-git path="/Environments" branch="main" secret-identifier="https://abndevcenterkeyvault.vault.azure.net/secrets/adopat" uri="https://dev.azure.com/damayantibhuyan/customerPOCs/_git/ade-demo" --name $(AZURE_CATALOG) --dev-center-name $(AZURE_ADE_NAME) --resource-group $(AZURE_RESOURCE_GROUP)'
    - task: AzureCLI@2
      displayName: Create Environment
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az devcenter dev environment create --dev-center-name $(AZURE_ADE_NAME) --environment-name $(ENVIRONMENT_NAME) --environment-type $(ENVIRONMENT_TYPE) --project $(AZURE_PROJECT) \
           --catalog-name $(AZURE_CATALOG) --environment-definition-name $(Environment_Definition_Name) 
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'masterconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          environment_rg=$(az devcenter dev environment show --name $(ENVIRONMENT_NAME) \
             --dev-center $(AZURE_ADE_NAME) --project $(AZURE_PROJECT) \
             --only-show-errors --query resourceGroupId --output tsv 2>&1)
          
           if [ $? -ne 0 ]; then
              echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
           fi
          
          environment_group=${environment_rg##*/}
          environment_sub=${environment_rg%/resourceGroups*}
          environment_sub=${environment_sub##*/}
          
          echo "ENVIRONMENT_GROUP=$environment_group" >> $ADO_ENV
          echo "ENVIRONMENT_SUB=$environment_sub" >> $ADO_ENV
          
          echo "- [View environment resources in the Azure portal](https://portal.azure.com/#@$(AZURE_TENANT_ID)/resource$environment_rg)" 
    
    

         
    
    